Revert "Set default value for github-token input"
This reverts commit dd45e36cd790fa5b380bc5a5cc3a6aab32e55352.

For some reason this does not work:

Error: artyom/post-pr-comment/v1/action.yml (Line: 10, Col: 19): Unrecognized named-value: 'github'. Located at position 1 within expression: github.token